week15-models-updated/config/routes.rb
Week15ModelsUpdated::Application.routes.draw do

  resources :users
end

week15-models-updated/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :age
end

week15-models-updated/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

week15-models-updated/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(:first_name => params[:first_name], :last_name => params[:last_name], :age => params[:age])
    @user.save
    redirect_to '/users'
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    render :text => "Hey! Updated successfully!!"
  end

end

week15-models-updated/app/helpers/application_helper.rb
module ApplicationHelper
end

week15-models-updated/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week15ModelsUpdated</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week15-models-updated/app/views/users/edit.html.erb
<h1> Editing a user</h1>
<%= form_for :user, url: user_path(@user.id), method: :put do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :age %>
    <%= f.text_field :age %>
    <%= f.submit "Save this!" %>
<% end %>

week15-models-updated/app/views/users/index.html.erb
<p>List of users</p>

<%= @users %>

<%= link_to "New user", new_user_path %>

week15-models-updated/app/views/users/new.html.erb
<form action="/users" method="post">
  <label for="first_name">First Name</label>
  <input name="first_name" type="TEXT" id="first_name">
  <br>
  <label for "last_name">Last Name</label>
  <input name="last_name" id="last_name" type="TEXT">
  <br>
  <label for "age">Age</label>
  <input name="age" id="age" type="TEXT">
  <br>
  <button type="submit">Save</button>
</form>

<%= link_to "All users", users_path %>

week15-models-updated/app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %>
<%= @user.age %>