week14-models-continued/config/routes.rb
Testapp::Application.routes.draw do

  match "/" => "home#index"
  match "users/new" => "users#new"
  match "users/" => "users#create"
  match "users/index" => "users#index"

  # STEP 1: tell your application which url should go to which
  # peice of code (config/routes.rb)

  # STEP 2: create controller with matching name for your route
  # e.g. home#index == home_controller.rb in app/controllers
  # and inside the file have: 
  # class HomeController < ApplicationController

  # STEP 3: create a folder in views that matches controller name
  # e.g. /views/home

  # STEP 4: create a file inside this new folder that matches
  # your function name: 
  # e.g. home#index == /views/home/index.html.erb

  # STEP 5: add code to html with: <%=...%> & <%...%>
  # STEP 6: share between controller/view with @

end

week14-models-continued/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@message = "This is the homepage"
	end

end

week14-models-continued/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new  
  end

  def create
    @user = User.new(params[:first_name => params[:first_name], :last_name => params[:last_name], :age => params[:age]])
    @user.save
    redirect_to '/users/index'
  end

  def index
    @users = User.all
  end

end

week14-models-continued/app/views/home/index.html.erb
<h1>this file exists in:</h1>
<h2>app/views/home/index.html.erb</h2>

<h1>
  <%= @message %>
</h1>

week14-models-continued/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week14-models-continued/app/views/shared/_shared_partial.html.erb
<h2>This is loaded from shared/_shared_partial.html.erb</h2>

week14-models-continued/app/views/users/index.html.erb
<p>List of users</p>

<%= @users %>

<%= link_to "New user", users_new_path %>

week14-models-continued/app/views/users/new.html.erb
<form action="/users" method="post">
      <label for="first_name" >First Name</label>
      <input name="first_name" type="TEXT" id="first_name">
      <br>
      <label for "last_name">Last Name</label>
      <input name ="last_name" id="last_name" type="TEXT">
      <br>
      <label for "age">Age</label>
      <input name ="age" id="age" type="TEXT">
      <br>
      <button type="submit">Save</button>
</form>

<%= link_to "All users", users_index_path %>